### ISSUE TITLE
Running hubot-aws on AWS Lambda?

### ISSUE THREAD

**Issue by EugeneLiang** [yoheimuta/hubot-aws#43]
Hi there, 

Awesome work!

I was wondering if there's a way to deploy hubot-aws on AWS Lambda ( in tandem with AWS API Gateway ) ? 

Best Regards.

**Comment by toadkicker** [comment]
AWS Lambda is designed for functions that have specific input, processing, and output lifetime. Hubot is a long running process listening and reacting to events. I don't think the external scripts can/should live in Lambda because of this design.

**Comment by stormlrd** [comment]
You could run it in a elastic beanstalk docker container however.

**Comment by yoheimuta** [comment]
Since time has passed, I will close it.
