### ISSUE TITLE
Update region environment variable from shell prompt

### ISSUE THREAD

**Issue by mullaiarasu** [yoheimuta/hubot-aws#53]
Hi,

We usually need to change the region for using services such lambda,ec2,etc., so I thought would'nt it be handy if we can change the region from shell prompt itself instead updating it in the local file and load it with hubot-env.  Can we add this feature ?

**Comment by yoheimuta** [comment]
Thanks, I understand it. 

> Can we add this feature ?

Yes. (of course, I think that it depends on the implementation)

**Comment by yoheimuta** [comment]
Since time has passed, I will close it.
