### ISSUE TITLE
How to add instance <public_ip> filed to `ec2 ls` output message?

### ISSUE THREAD

**Issue by lazysa** [yoheimuta/hubot-aws#55]
Hi，I found no instance <public_ip> filed when run `ec2 ls`
eg：
> time	state	id	image	az	subnet	type	ip	name

how to add it，thanks

**Comment by yoheimuta** [comment]
Yes. It seems that we should make a PR to add public-ip here. If you need it immediately, please create a PR.

- https://github.com/yoheimuta/hubot-aws/blob/906b4fe33597dfdf9ea28c67548f214d227a731f/scripts/ec2/ls.coffee#L75

**Comment by lazysa** [comment]
Yean，I have installed it by npm. 
What is PR ?  need add new line in `ls.coffee` ? or replace you pick out line ?

**Comment by yoheimuta** [comment]
> need add new line in ls.coffee ?

Yes, It means this.

**Comment by lazysa** [comment]
OK，
https://github.com/yoheimuta/hubot-aws/pull/57
